### PR TITLE
initial attempt to port to 7.0.1

### PR DESCRIPTION
**Pull request by typerlc**
Ok, I've made an attempt at porting.

However, there are still some issues.  Everything compiles, but an exception is thrown when starting the Example wizard.

There are 2 places I've made changes I'm not 100% sure about:

```
diff --git a/modules/gui/src/de/diedavids/cuba/wizard/gui/xml/layout/loaders/WizardStepLoader.java b/modules/gui/src/de/diedavids/cuba/wizard/gui/xml/layout/loaders/WizardStepLoader.java

-        resultComponent = (WizardStep) factory.createComponent(WizardStep.NAME);
+        resultComponent = (WizardStep) componentsFactory.createComponent(WizardStep.NAME);
```

I'm not sure where `factory` came from before (it wasn't compiling).  There were a few lines where I made this change.

```
diff --git a/modules/web/src/de/diedavids/cuba/wizard/web/gui/components/WebWizardStep.java b/modules/web/src/de/diedavids/cuba/wizard/web/gui/components/WebWizardStep.java

-public class WebWizardStep extends WebVBoxLayout implements WizardStep {
+public class WebWizardStep extends WebFragment implements WizardStep {
     private String name;
     private WizardStepAware stepComponent;
     private TabSheet.Tab tabComponent;
@@ -66,7 +66,7 @@ public class WebWizardStep extends WebVBoxLayout implements WizardStep {

     private WizardStepAware getWizardStepAware() {
         if (ownComponents.size() > 0) {
-            return (WizardStepAware) ownComponents.get(0);
+            return ((WebWizardStep)ownComponents.get(0)).stepComponent;
         }
         else {
             return stepComponent;
```

I'm really not sure about this.  Line 66 is where the exception is being thrown.  It is saying that it can't cast an instance of ....WebFragment to ...WizardStepAware.

### CODE REVIEW

**Comment by mariodavid** [comment]
hi,

thanks for reaching out! I will try to take a look at it.

What about this change here: https://github.com/mariodavid/cuba-component-wizard/pull/8/files#diff-e0c4ff239857dc7827ba4fe4ec3c1024R9

I'm actually not sure :)


Bye
Mario

**Comment by tcolemancas** [comment]
Hi Mario, 

I had also attempted to port to 7.x similarly to @typerlc 's port above, 

I got the same errors from the attempts to cast from WebFragment to WebStepAware, 

Looking into the causes it appears that the inheritance from parent classes shared between WebFragment to AbstractFrame have changed in versions 7.x, 

I wasn't sure if it might have been possible to add a function to the WizardStepLoader to allow the WizardStep implementation to be cast to WizardStepAware at runtime etc, but (in terms of a simple port) I didn't manage to find any shared components that AbstractFrame has with other web components that WebWizardStep could extend to maintain the same logic, 

I had hoped to be able to do a simple port and just update some of the classes to replicate the same behavior by using the newer API's in version 7.x but sadly it seems (at least from looking at it) that some important portions may need to be redesigned, 

Anyway I thought it might be useful to you outline what I found from attempting to port it across to 7.x,

Cheers, 

-T

**Comment by mariodavid** [comment]
hi,

thanks both of you for taking a try to update it.

I've looked at the PR and it seems that you are right @tcolemancas - it seems that there some not so easy to resolve changes. Actually I expected this to happen for this app component unfortunately.

I haven't made up my mind on how to solve this - but I would be more then happy if you come up with just some ideas on how to solve it. Even if this means breaking changes, it does not really matter at this stage of the app component.

Bye
Mario

**Comment by ZuperKeurZ** [comment]
Hi, I started on another upgrade attempt without even seeing this one.

I made a pull request for it. My version uses the v7 api though so it's not fully backwards compatible. More info in the forum discussion https://www.cuba-platform.com/discuss/t/cuba-component-wizard-preview/6617/4

**Comment by ZuperKeurZ** [comment]
@typerlc, @tcolemancas & @mariodavid can you have a look at my pull request. It's not using the old api, but at least for the included sample it seems to work with some changes for using the new api (eg. @Inject Notifications).

Not sure if more complex flows would also work. Would it be acceptable for you guys to to migrate or do you require full backwards compatiblity?

regards,
Tom

**Comment by mariodavid** [comment]
Hi,

i've taken this PR as a basis and fixed the class cast exception via some internal casting compatible to CUBA 7.0. See: https://github.com/mariodavid/cuba-component-wizard/pull/10

**Comment by mariodavid** [comment]
I'll close this PR as the other one contains the sources from here.

Thanks again @typerlc & @tcolemancas for the collaboration. Really appreciate it!

**Pull request closed without merging**
