### PR TITLE
another try with a wizard step component

### PR DESCRIPTION
**Pull request by mariodavid**
Another approach is to create Component `WizardStep` and use it in a composite way. I also looked at `Accordion` and `Accordion.Tab` but i'm not really sure how to call `createSubComponents` and `loadSubComponents` correctly... :-(

### CODE REVIEW

**Comment by mariodavid** [comment]
bildschirmfoto 2018-05-12 um 13 03 17

**Comment by mariodavid** [comment]
it gets rendered, but the frame content is underneath the tabs and not within them...

**Review by jreznot — COMMENTED** [review]
Generally speaking, TabSheet and Tab should be internal parts of the Wizard component and not just XML based.

The main bug here with Tabs is the excessive createSubComponents call.

**Comment by jreznot** [comment]
Apply this patch and it will work

[Patch_for_nested_frames_loading.patch.txt](https://github.com/mariodavid/cuba-component-wizard/files/2008935/Patch_for_nested_frames_loading.patch.txt)

**Comment by mariodavid** [comment]
Ah, ok thanks.

I still don't fully understand what the problem with that is, but thats ok :)

> Generally speaking, TabSheet and Tab should be internal parts of the Wizard component and not just XML based.

What do you mean by that?
In the example XML there is nothing about tabs:
```
        <wizard:wizard id="wizardPanel" height="100%">
            <wizard:step caption="Step 1" screen="example-1-step-1-frame" />
            <wizard:step caption="Step 2" screen="example-1-step-2-frame" />
        </wizard:wizard>
```

Or do you mean it should be hidden in the `WebWizard` class?

**Comment by jreznot** [comment]
I mean they should be implemented in the UI component and not in component loader. For instance, if we add steps programmatically then component loader will not be used

**Comment by mariodavid** [comment]
Ok, so if I get you right, you mean that I should deal with the creation of a TabSheet or an Accordion in [Wizard](https://github.com/mariodavid/cuba-component-wizard/blob/master/modules/gui/src/de/diedavids/cuba/wizard/gui/components/Wizard.java#L5) and [WebWizard](https://github.com/mariodavid/cuba-component-wizard/blob/master/modules/web/src/de/diedavids/cuba/wizard/web/gui/components/WebWizard.java) - is that correct? This makes total sense because of programmatic creation. Just like here e.g.: [Accordion.addTab](https://github.com/cuba-platform/cuba/blob/master/modules/gui/src/com/haulmont/cuba/gui/components/Accordion.java#L40)- correct?

But:
Compared to all other CUBA Components, in this Wizard Component i would like to not dig down in the  Vaadin layer, because there is no need to. If I see it correctly, the only place where I could place the implementation would be the `WebWizard` class. But there I'm already in Vaadin land and cannot use stuff like CUBA Accordion, correct?

Does this mean that I have to use the native Vaarin accordion to accomplish it?

Or is it possible to create a `WizardImpl` in the `gui` module and interact there with the CUBA components like `Accordion`.

If this is not possible, that I might loose some benefits of the abstraction you have put in place with something like `Accordion`...

Perhaps you can bring some light into this ;)

**Comment by mariodavid** [comment]
hi @jreznot, 

do you have an idea on my above question? Perhaps I will just start and see how it goes, but I just want to make sure that I not totally misunderstand something here...

Thanks,
Mario

**Comment by jreznot** [comment]
I mean that your component should contain TabSheet as the implementation detail. You can use cuba components if you do not want depend on Vaadin ones, for instance, Filter component uses GUI components instead of Vaadin. You can even implement your component in `gui` module, but it is not required.

As for Accordion and TabSheet - I think it is not so good idea to use them for Wizard at all. They use excessive space and it is not usual design pattern for wizards.

**Pull request merged**
